/*
===============================================================
 #CUSTOM JavaScript
- Please do not edit this file. This file is generated from admin area.
- Every changes here will be overwritten by theme
===============================================================*/
    /* theme_options_custom 
=========================*/
 document.querySelectorAll(".col-theme-icons .elementor-icon").forEach(link => {
  link.addEventListener("focus", () => link.closest('.elementor-widget-container').classList.toggle("focus"));
  link.addEventListener("blur", () => link.closest('.elementor-widget-container').classList.toggle("focus"));
 });
 
 (function() {
    fixCgpApiSearchUrl();
})();

function fixCgpApiSearchUrl() {
    let cgpAPIforms = document.querySelectorAll('.cgp-custom-api-search-form');
    if (0 === cgpAPIforms.length) {
        return;
    }
    for (let cgpAPIform of cgpAPIforms) {
        cgpAPIform.addEventListener('submit', function(submitEvent) {
            submitEvent.preventDefault();
            let actionVal = cgpAPIform.getAttribute('action');
            let keywordOnlyEl = cgpAPIform.querySelector('.cgp-api-keyword-only');
            let langVal = "en";
            let langValEl = cgpAPIform.querySelector('.cgp-api-lang');
            if (null !== langValEl) {
                langVal = langValEl.value
            }
            let themeVal = "";
            let themeValEl = cgpAPIform.querySelector('.cgp-api-theme');
            if (null !== themeValEl) {
                themeVal = themeValEl.value
            }
            let keywordVal = cgpAPIform.querySelector('.cgp-api-keyword').value;
            let newActionVal = `${actionVal}?lang=${langVal}&theme=${themeVal}&keyword=${keywordVal}`;
            if( themeVal === "" ) {
                newActionVal = `${actionVal}?lang=${langVal}&keyword=${keywordVal}`;
            }
            if (null !== keywordOnlyEl) {
                let keywordOnlyVal = keywordOnlyEl.value
                newActionVal += `&keyword_only=${keywordOnlyVal}`;
            }
            newActionVal = decodeURIComponent(newActionVal.replace(/\+/g, ' '));
            window.location.href = newActionVal;
        });
    }
}
